---
title: Operaciones con fechas en R usando `{lubridate}`
author: Bastián Olea Herrera
date: '2026-09-01'
slug: []
categories: []
tags:
  - fechas
draft: true
format:
  hugo-md:
    output-file: index
    output-ext: md
execute:
  message: false
  warning: false
excerpt: Resumen del post
links:
  - icon: file-code
    icon_pack: fas
    name: Código
    url: https://github.com/bastianolea
---

```r
install.packages("lubridate")
```



```{r}
library(lubridate)
```

días para el 18

```{r}
today()
```

```{r}
now()
```


```{r}
dieciocho <- as_date("2026-09-18")
```

```{r}
días <- dieciocho - today()

días
```

al momento de escribir esta publicación, faltan `{r} días` días para el dieciocho de septiembre


```{r}
now() + hours(6)
```

```{r}
now() |> as_date()
```



Este año febrero tuvo 28 días.

```{r}
as_date("2026-02-28") + days(1)
```


```{r}
fechas <- c("2024-05-12", "2025-02-28", "2026-01-13")

fechas <- as_date(fechas)

year(fechas)
```


Días de la semana

```{r}
lubridate::wday(secuencia, week_start = 1)
```

Un 5 va a ser viernes


{{< etiqueta "fechas" >}}