---
title: Crea mapas bivariados en R para visualizar la relación entre dos variables
author: Bastián Olea Herrera
date: '2026-04-29'
slug: []
draft: true
categories:
  - Tutoriales
tags:
  - mapas
  - visualización de datos
format:
  hugo-md:
    output-file: index
    output-ext: md
---


```{r}
library(dplyr)
library(tidyr)
library(arrow)

# cargar ----
comunas <- readxl::read_xlsx("~/Documents/Datos/Censo/2024/diccionario_variables_censo2024.xlsx",
                             sheet = "codigos_territoriales") |> 
  select(comuna = 1, nombre_comuna = 3) |> 
  filter(comuna > 999)

personas <- open_dataset("~/Documents/Datos/Censo/2024/personas_censo2024.parquet")

hogares <- open_dataset("~/Documents/Datos/Censo/2024/hogares_censo2024.parquet")


# personas: seleccionar columnas
personas_filt <- personas |>
  select(id_vivienda, id_hogar, comuna, parentesco,
         sexo, edad_quinquenal)

# hogares: seleccionar columnas
hogares_filt <- hogares |>
  select(id_vivienda, id_hogar, comuna, p12_tenencia_viv)

# cruzar ambas bases por hogar/vivienda/comuna
personas_hogares <- personas_filt |> 
  left_join(hogares_filt, 
            join_by(id_vivienda, id_hogar, comuna))
# resultado: base de personas con datos de la vivienda donde viven

# conteo ----
conteo <- personas_hogares |> 
  group_by(comuna, sexo, edad_quinquenal, parentesco, p12_tenencia_viv) |> 
  summarize(n = n()) |> 
  ungroup() |> 
  collect() # carga a memoria de los datos


# recodificación ----
conteo_recod <- conteo |> 
  mutate(parentesco = recode_values(
    parentesco,
    1 ~	"Jefe/a de hogar",
    2 ~	"Esposo/a o cónyuge",
    default = "Otros")) |> 
  mutate(sexo = recode_values(
    sexo, 
    1 ~ "Hombre", 
    2 ~ "Mujer")) |> 
  mutate(p12_tenencia_viv = recode_values(
    p12_tenencia_viv, 
    1 ~ "Propia pagada",
    2 ~ "Propia pagándose",
    3 ~ "Arrendada con contrato",
    4 ~ "Arrendada sin contrato",
    5 ~ "Cedida por trabajo o servicio",
    6 ~ "Cedida por familiar u otro",
    7 ~ "Usufructo: solo uso y goce",
    8 ~ "Ocupada de hecho",
    9 ~ "Propiedad en sucesión o litigio")) |> 
  mutate(propiedad = if_else(
    p12_tenencia_viv %in% c("Propia pagada", "Propia pagándose"), 
    "Propia", "No propia")) |> 
  mutate(mayor = case_when(sexo == "Hombre" & edad_quinquenal >= 65 ~ "Adulto mayor", 
                           sexo == "Mujer" & edad_quinquenal >= 60 ~ "Adulto mayor",
                           .default = "No adulto mayor")) |> 
  left_join(comunas, by = "comuna") |> 
  relocate(nombre_comuna, .before = comuna)


# calcular ----

# porcentaje de adultos mayores por comuna
comuna_mayor <- conteo_recod |> 
  group_by(nombre_comuna, comuna) |> 
  count(mayor) |> 
  mutate(p = n / sum(n)) |> 
  filter(mayor == "Adulto mayor") |> 
  ungroup()

comuna_propia <- conteo_recod |> 
  group_by(nombre_comuna, comuna) |> 
  count(propiedad) |> 
  mutate(p = n / sum(n)) |> 
  filter(propiedad == "Propia") |> 
  ungroup()

# unir
datos_censo <- left_join(
# datos adulto mayor
  comuna_mayor |> 
    select(nombre_comuna, comuna,
           mayor_p = p),
  # datos propiedad
  comuna_propia |> 
    select(comuna,
           propia_p = p)
)

datos_censo

```


```{r}
library(ggplot2)
library(sf)
library(chilemapas)
library(patchwork)

source("datos_censo.R")

# https://timogrossenbacher.ch/bivariate-maps-with-ggplot2-and-sf/
# https://www.joshuastevens.net/cartography/make-a-bivariate-choropleth-map/
# https://www.datawim.com/post/creating-professional-bivariate-maps-in-r/
# https://jakubnowosad.com/posts/2020-08-25-cbc-bp2/

mapa_comunas <- chilemapas::mapa_comunas |> 
  mutate(codigo_comuna = as.numeric(codigo_comuna),
         codigo_region = as.numeric(codigo_region)) |> 
  select(-codigo_provincia) |> 
  rename(region = codigo_region,
         comuna = codigo_comuna)

mapa_censo <- datos_censo |> 
  left_join(mapa_comunas,
            by = join_by(comuna))

# chilemapas::mapa_comunas |> st_as_sf()

mapa_censo |> 
  filter(region == 7)

# install.packages("biscale")
library(biscale)

regiones <- 13
dimensiones <- 4

mapa_censo_bi <- mapa_censo |> 
  filter(region == regiones) |> 
  bi_class(x = mayor_p, 
         y = propia_p, 
         style = "quantile", dim = dimensiones)

paleta <- "BlueOr"
paleta <- "DkBlue"
paleta <- "DkViolet2"


# gráfico
mapa <- mapa_censo_bi |> 
  st_as_sf() |> 
  ggplot() +
  aes(fill = bi_class) +
  geom_sf(show.legend = FALSE,
          linewidth = 0.1, color = "white") +
  # escala vibariada
  bi_scale_fill(pal = paleta, dim = dimensiones, 
                flip_axes = FALSE, rotate_pal = FALSE) +
  theme_minimal()


legend <- bi_legend(pal = paleta,   
                    flip_axes = FALSE,
                    rotate_pal = FALSE,
                    dim = dimensiones,
                    xlab = "Adultos mayores",
                    ylab = "Viviendas propias",
                    size = 6) +
  theme(plot.background = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank())



mapa + 
  theme_void() +
  inset_element(legend, 
                left = 0, bottom = 0.7, 
                right = 0.3, top = 1) +
  ggview::canvas(6, 5)


```

